[custom.all.css]
type = "local"
path = "."
ipkg = "css.ipkg"

[custom.all.literal]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-literal"
commit = "latest:main"
ipkg   = "literal.ipkg"
